{{- if and .Values.global.metric.enabled .Values.telegraf.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pinpoint.fullname" . }}-telegraf-config
  labels:
    {{- include "pinpoint.labels" . | nindent 4 }}
    app.kubernetes.io/component: telegraf
data:
  telegraf.conf: |
{{- $path := printf "files/telegraf/%s/pinpoint-telegraf.conf" .Values.global.pinpointVersion }}
{{- $config := required "No bundled Telegraf configuration for global.pinpointVersion" (.Files.Get $path) }}
{{ $config | replace "127.0.0.1" (printf "%s-collector" (include "pinpoint.fullname" .)) | indent 4 }}
{{- end }}
